### ISSUE TITLE
Real-time video detection

### ISSUE THREAD

**Issue by sunpudding** [rdeepc/ExploreOpencvDnn#2]
hello，Can this be Video detected in real time，use picamera?

**Comment by rdeepc** [comment]
Yes, You can use any image input

**Comment by sunpudding** [comment]
Wow, Glad to receive your letter,Do you have any code to give me a reference.Because my programming ability is poor.

**Comment by rdeepc** [comment]
https://www.pyimagesearch.com/2015/03/30/accessing-the-raspberry-pi-camera-with-opencv-and-python/

**Comment by sunpudding** [comment]
Thank you very much, I will study it seriously .o((≧▽≦o)o.
